/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzleDayRouteImport } from './routes/puzzle.$day'
import { Route as PuzzleDayVisualizationRouteImport } from './routes/puzzle.$day.visualization'
import { Route as PuzzleDaySolveRouteImport } from './routes/puzzle.$day.solve'
import { Route as PuzzleDayInputRouteImport } from './routes/puzzle.$day.input'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleDayRoute = PuzzleDayRouteImport.update({
  id: '/puzzle/$day',
  path: '/puzzle/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzleDayVisualizationRoute = PuzzleDayVisualizationRouteImport.update({
  id: '/visualization',
  path: '/visualization',
  getParentRoute: () => PuzzleDayRoute,
} as any)
const PuzzleDaySolveRoute = PuzzleDaySolveRouteImport.update({
  id: '/solve',
  path: '/solve',
  getParentRoute: () => PuzzleDayRoute,
} as any)
const PuzzleDayInputRoute = PuzzleDayInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => PuzzleDayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/puzzle/$day': typeof PuzzleDayRouteWithChildren
  '/puzzle/$day/input': typeof PuzzleDayInputRoute
  '/puzzle/$day/solve': typeof PuzzleDaySolveRoute
  '/puzzle/$day/visualization': typeof PuzzleDayVisualizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/puzzle/$day': typeof PuzzleDayRouteWithChildren
  '/puzzle/$day/input': typeof PuzzleDayInputRoute
  '/puzzle/$day/solve': typeof PuzzleDaySolveRoute
  '/puzzle/$day/visualization': typeof PuzzleDayVisualizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/puzzle/$day': typeof PuzzleDayRouteWithChildren
  '/puzzle/$day/input': typeof PuzzleDayInputRoute
  '/puzzle/$day/solve': typeof PuzzleDaySolveRoute
  '/puzzle/$day/visualization': typeof PuzzleDayVisualizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/puzzle/$day'
    | '/puzzle/$day/input'
    | '/puzzle/$day/solve'
    | '/puzzle/$day/visualization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/puzzle/$day'
    | '/puzzle/$day/input'
    | '/puzzle/$day/solve'
    | '/puzzle/$day/visualization'
  id:
    | '__root__'
    | '/'
    | '/puzzle/$day'
    | '/puzzle/$day/input'
    | '/puzzle/$day/solve'
    | '/puzzle/$day/visualization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PuzzleDayRoute: typeof PuzzleDayRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$day': {
      id: '/puzzle/$day'
      path: '/puzzle/$day'
      fullPath: '/puzzle/$day'
      preLoaderRoute: typeof PuzzleDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzle/$day/visualization': {
      id: '/puzzle/$day/visualization'
      path: '/visualization'
      fullPath: '/puzzle/$day/visualization'
      preLoaderRoute: typeof PuzzleDayVisualizationRouteImport
      parentRoute: typeof PuzzleDayRoute
    }
    '/puzzle/$day/solve': {
      id: '/puzzle/$day/solve'
      path: '/solve'
      fullPath: '/puzzle/$day/solve'
      preLoaderRoute: typeof PuzzleDaySolveRouteImport
      parentRoute: typeof PuzzleDayRoute
    }
    '/puzzle/$day/input': {
      id: '/puzzle/$day/input'
      path: '/input'
      fullPath: '/puzzle/$day/input'
      preLoaderRoute: typeof PuzzleDayInputRouteImport
      parentRoute: typeof PuzzleDayRoute
    }
  }
}

interface PuzzleDayRouteChildren {
  PuzzleDayInputRoute: typeof PuzzleDayInputRoute
  PuzzleDaySolveRoute: typeof PuzzleDaySolveRoute
  PuzzleDayVisualizationRoute: typeof PuzzleDayVisualizationRoute
}

const PuzzleDayRouteChildren: PuzzleDayRouteChildren = {
  PuzzleDayInputRoute: PuzzleDayInputRoute,
  PuzzleDaySolveRoute: PuzzleDaySolveRoute,
  PuzzleDayVisualizationRoute: PuzzleDayVisualizationRoute,
}

const PuzzleDayRouteWithChildren = PuzzleDayRoute._addFileChildren(
  PuzzleDayRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PuzzleDayRoute: PuzzleDayRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
